pipeline {
  agent {
    label 'docker-agent'
  }

  environment {
    DOCKER_BUILDKIT = "1"
    REGISTRY = "registry.local:5000"
    IMAGE_NAME = "${env.REPO_NAME}"
    IMAGE_TAG = "${env.COMMIT_ID}"
    FULL_IMAGE = "${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
    REPO_OWNER = "${env.REPO_OWNER}"
    APP_PATH = "apps/${IMAGE_NAME}/overlays/prod"
  }

  options {
    skipDefaultCheckout()
    disableConcurrentBuilds()
  }

  stages {
    stage("Info") {
      steps {
        echo "Repo: ${IMAGE_NAME}"
        echo "Commit Id: ${IMAGE_TAG}"
        echo "Branch: ${env.BRANCH}"
        echo "Owner: ${env.REPO_OWNER}"
      }
    }

    stage('Validate Env') {
      steps {
        script {
          ['REPO_NAME','COMMIT_ID'].each {
            if (!env[it]) error("Missing env var: ${it}")
          }
        }
      }
    }

    stage('Preparation') {
        steps {
            sh '''
            which git || echo "git missing"
            docker version
            '''
        }
    }

    stage('Checkout') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: '*/main']],
          userRemoteConfigs: [[
            url: "http://gitea.local:3000/alfathmuqoddas/${IMAGE_NAME}.git",
            credentialsId: 'gitea-cred'
          ]]
        ])
      }
    }

    stage('Build Image') {
      steps {
        sh """
          docker build -t ${FULL_IMAGE} .
        """
      }
    }

    stage('Push Image') {
      steps {
        sh """
          docker push ${FULL_IMAGE}
        """
      }
    }

    stage('Checkout GitOps Repo') {
      steps {
        dir('gitops') {
          checkout([
            $class: 'GitSCM',
            branches: [[name: '*/main']],
            doGenerateSubmoduleConfigurations: false,
            extensions: [
              [$class: 'LocalBranch', localBranch: 'main']
            ],
            userRemoteConfigs: [[
              url: 'http://gitea.local:3000/alfathmuqoddas/behemoth-app-manifest.git',
              credentialsId: 'gitea-cred'
            ]]
          ])
        }
      }
    }


    stage('Update GitOps Repo') {
      steps {
        dir("gitops/${APP_PATH}") {
          withCredentials([usernamePassword(
            credentialsId: 'gitea-cred',
            usernameVariable: 'GIT_USER',
            passwordVariable: 'GIT_PASS'
          )]) {
            sh """
              git config user.name "jenkins"
              git config user.email "jenkins@local"

              yq -i '
                .images[] |=
                select(.name == "${IMAGE_NAME}") |
                .newTag = "${IMAGE_TAG}"
              ' kustomization.yaml

              git add kustomization.yaml
              git commit -m "deploy(${IMAGE_NAME}): ${IMAGE_TAG}" || echo "No changes to commit"

              git push http://${GIT_USER}:${GIT_PASS}@gitea.local:3000/alfathmuqoddas/behemoth-app-manifest.git main
            """
          }
        }
      }
    }



  }

  post {
    always {
      echo "Cleaning workspace"
      cleanWs(deleteDirs: true, disableDeferredWipeout: true)
    }
    failure {
      echo "Build failed"
    }
    success {
      echo "Image pushed: ${FULL_IMAGE}"
    }
  }
}
